---
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Generic EMR template. This creates an EMR cluster using DOS CI/CD with help from the 'Include' Transform in CloudFormation.
Parameters:
  ApplicationPrefix:
    Description: Prefix to identify the team.  (i.e. platform, ca, etc.)
    Type: String
  StageName: #Required. Do not remove. The CI/CD pipeline will pass in the appropriate value.
    Type: String
    Default: stage
    AllowedValues: [dev, stage, prod]
  MappingsPath:
    Description: Path for team mappings (cicd buckets, etc.) Included in AWS Transform below.
    Type: String
  AdditionalEMRPropertiesPath:
    Description: Path for EMR Properties (Bootstrap Actions,Applications,etc.) Included in AWS Transform below.
    Type: String
  AdditionalEMRResourcesPath:
    Description: Path for additional EMR resources a team might have(Steps, InstanceGroupConfig, etc.). Included in AWS Transform below.
    Type: String
#This is a mappings file for team-based buckets, etc.
Mappings:
  'Fn::Transform':
    Name: 'AWS::Include'
    Parameters:
      Location: !Sub 's3://med-av-daas-preprod-${ApplicationPrefix}-cicd/emr/config/${AWS::StackName}/${MappingsPath}'

Resources:
  EMRCluster:
    Type: AWS::EMR::Cluster
    Properties:

      #This includes all the EMR properties.
      'Fn::Transform':
        Name: 'AWS::Include'
        Parameters:
          Location: !Sub 's3://med-av-daas-preprod-${ApplicationPrefix}-cicd/emr/config/${AWS::StackName}/${AdditionalEMRPropertiesPath}'

  #This includes any additional EMR-related resources you may need.
  'Fn::Transform':
    Name: 'AWS::Include'
    Parameters:
      Location: !Sub 's3://med-av-daas-preprod-${ApplicationPrefix}-cicd/emr/config/${AWS::StackName}/${AdditionalEMRResourcesPath}'